spring:
  application:
    name: ecommerce
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog_db
      auto-index-creation: true
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    context-path: /api

# Paginaci√≥n por defecto
app:
  pagination:
    default-page-size: 20
    max-page-size: 100

# Swagger/OpenAPI
spring-doc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true